# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn install -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_NEW }}
  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Test Input Handler
        run: mvn test -Dtest="InputHandlerTests"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_NEW }}
      - name: Test LngLat Handler
        run: mvn test -Dtest="LngLatHandlingTests"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_NEW }}
      - name: Test Order Validator
        run: mvn test -Dtest="OrderValidatorTests"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_NEW }}
      - name: Test Retriever
        run: mvn test -Dtest="RetrieverTests"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_NEW }}
  system-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Test App running
        run: mvn test -Dtest="AppTest"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_NEW }}
  all-tests:
    needs: system-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Test with mvn
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_NEW }}
